### ISSUE TITLE
Potential Error in BrioWuShockTube/SingleFluidIdealParallel example

### ISSUE THREAD

**Issue by aniabrown** [AlexJamesWright/METHOD#12]
When this is run on 4 procs, there is one report of smart guessing not working in the run. This does not occur in the serial version. The parallel and serial versions do give the same results to within a tolerance of 10e-15. 

Need to confirm if smart guessing should be being attempted in this run. If so, need to implement smart guessing in parallel. 

```
t = 0.217000
Smart guessing did not work, exiting
(1, 0, 0) failed
```

**Comment by AlexJamesWright** [comment]
Thats in a ghost zone, so may not be important. The C2P is only important for the interior and immediately after its finished the physical BCs are applied

**Comment by IanHawke** [comment]
There are possible issues with only applying C2P for the interior (although I don't think any apply to our models: examples would be if you're applying an atmosphere algorithm during the evolution step, and that ends up being done after communication, so ghost zones need correcting).

I would suggest that there's a parameter to say whether C2P is applied to ghosts or not, but it should default to not.

**Comment by aniabrown** [comment]
That helps, thanks. 

I've gone and had a look that this wasn't failing at the ghost cells due to something being wrong with the boundary exchange, but that appears to be in order for this example. I think what is happening is that flux reconstruction is only applied to some of the ghost cells, whereas C2P is applied for all ghost cells. This seems to cause a small number of the ghost cells that didn't have the flux reconstruction done to them to fail. There are more occasions for this to happen with the multi process version as there are all the internal boundaries between procs in addition to the external boundaries, which I guess is why we're not seeing this failure in the serial case?

If that's what's really going on, I'd suggest doing the C2P for the innermost layer of ghost cells, to have something to average over if any of the interior cells fail.

**Comment by IanHawke** [comment]
Right, yes. In principle there should be the flux update modifying the conserved variables, then a parallel sync of the conserved, then the C2P, then a parallel sync of the prims. That's because, in an ideal world, the ghost zones should never be updated (and hence should be considered wrong) by the flux evolution step.

However, it's never going to be the ideal world, so an approach that applies C2P only to the interior by default and then does a single sync is more efficient in all ways, and any code that needs to care about having correct conserved variables in ghostzones after updates will need to be explicit about that.

**Comment by AlexJamesWright** [comment]
Good-o, there is no code run between the update and the BCs other than the C2P, so an update, a C2P on the interior cells and then an exchange will work. Ill make sure this is the case for all models.

**Comment by AlexJamesWright** [comment]
I have committed the changes to the master branch for solving only the interior cells. If you merge master with the MPI branch and run this problem again hopefully we wont see it.
