### ISSUE TITLE
WENO order

### ISSUE THREAD

**Issue by AlexJamesWright** [AlexJamesWright/METHOD#20]
FVS has WENO3 hard coded, would be nice to be able to select the order.

**Comment by IanHawke** [comment]
Note in my vector_potential branch there is some work on this (eg https://github.com/IanHawke/METHOD/commit/1356df7c45710b3d5d0ffbbbd78dc5b0ea42edea or https://github.com/IanHawke/METHOD/blob/vector_potential/weno-coefficients.ipynb) but it's a long way from working. It's likely that characteristic reconstruction will be needed for higher order.

**Comment by AlexJamesWright** [comment]
Ian, your script for generating the weno.cc is voodoo magic. I will have a play with this and include it in the Serial dir once I have a draft to you. Will look at implementing some higher order RKs too

**Comment by AlexJamesWright** [comment]
I've implemented all the wenos from your script, can go higher easily but doesnt seem to be any point. Also implemented the SSPRK(2,2) (3,3) (4,5) and (4,10). 
(2,2) gives the same results (more or less) as RKSplit2 which is encouraging.
(3,3) is average/solid
(4,5) can use CFLs of 1.7 for smooth data (I've implemented an AdvectionSingleFluid initial data to assess the convergence properties)
(4,10) can use CFLs of 3.6, basically the same efficiency as (4,5) though, or maybe a little more expensive.

**Comment by IanHawke** [comment]
I guess the limiting factor is going to be how they do on eg Brio-Wu.

**Comment by AlexJamesWright** [comment]
A quick look suggests RK(4,5) is more stable for BW, managing around cfl=2.1 before obvious Gibbs when using weno7---higher order weno needs smaller cfl. For comparison, RK(4,10) needs cfl<1 for comparable results with same parameters, so all in all is >3x less efficient in this case.

I will do a once over of the branch tomorrow and if all is well will merge it

**Comment by AlexJamesWright** [comment]
Finished in dacc383d4
