### ISSUE TITLE
GPU/Serial comparison

### ISSUE THREAD

**Issue by AlexJamesWright** [AlexJamesWright/METHOD#26]
So I've had a look at the GPU tests and on my machine that are all passing now. Not sure what was causing them to fail, I changed a few things to deal with only saving the interior data and they now pass on my machine (eb8bb9e0). You can check if they are passing with your setup now, and if they are they can go in master. 
FYI the changes I made are on a separate branch: gpu_alex

**Comment by aniabrown** [comment]
This is weird -- the tests do pass on my system but the (as far as I can tell) same simulation running in the GPU and CPU Project directories do not give the same answer. 

I've added the SSP2FlowKHSingleFluid unit test, which is taken from Project/Src/main.cu with a few parameters changed to match the unit tests (smaller nx, endTime etc). That test passes but the same simulation in the project directory doesn't seem to match the CPU data. I've pushed my new unit test and the changes to Project/CPU/Src/main.cpp and Project/GPU/Src/main.cu to the gpu_alex branch -- can you see if I'm missing something obvious?

**Comment by AlexJamesWright** [comment]
Is it because the magnetic fields are set to zero in the CPU main.cc? Try using `KHInstabilitySingleFluid(&data, 1)` instead

**Comment by AlexJamesWright** [comment]
Problem was in the GPU code I wasnt setting the electric fields in the same way as in the CPU branch (and the magnetic fields comment above too). Also you were doing a lot of iterations and there was a build up of error even after this was corrected. I think it should be good now. Let me know if it's not

**Comment by aniabrown** [comment]
Ah, that makes sense, thanks. Waiting on an iridis job to confirm.

**Comment by aniabrown** [comment]
That's working now, thanks!
