### ISSUE TITLE
Data object constructor interface is unwieldy 

### ISSUE THREAD

**Issue by aniabrown** [AlexJamesWright/METHOD#34]
The current Data constructor takes 11 required args and an additional 11 optional args. As c++ optional args are purely position based, this means that if you want to use the 11th optional arg but none of the others, you still have to include all of them, leading to very long constructor lines which are easy to make a mistake in. It would be good to have a more user friendly solution.

**Comment by aniabrown** [comment]
c++ doesn't appear to have a perfect solution to this, but the closest you can get to named, reorderable parameters involves chained setter functions attached to a constructor. See -- https://isocpp.org/wiki/faq/ctors#named-parameter-idiom. 

We need to tweak the method described in the link a little as we need the Data object to do some initialisation work as a last step after all the object parameters have been set. This could either be done by 1) constructing a parameter object that only sets all parameters, then passing that object to the Data constructor, which would perform the initialisation work, or 2) by only setting the object parameters in the Data constructor, and then calling a Data::init() function later. I've chosen option 1 as that doesn't break any code that uses the old constructor, and because that approach matches the approach for creating a data object from an object of parameters read from a restart file. 

The new interface looks like this:

```
DataArgs dataArgs = DataArgs(nx, ny, nz, xmin, xmax, ymin, ymax, zmin, zmax, endTime)
        .sCfl(cfl).sNg(Ng).sGamma(gamma).sCp(cp).sMu1(mu1).sMu2(mu2).sFrameSkip(frameSkip).sSigma(sigma)
Data data = Data(dataArgs, &env);
```
Where the required args are set in the DataArgs constructor, and all other args are set in chained setters. Any of the setters can be left off to use the default value and they can be applied in any order. 

Initialising Data from a checkpoint restart file is similar:

```
ParallelCheckpointArgs checkpointArgs = ParallelCheckpointArgs(filename, &env).sEndTime(endTime)
        .sMu1(mu1).sMu2(mu2).sFrameSkip(frameSkip).sReportItersPeriod(reportItersPeriod);
Data data = Data(checkpointArgs, &env);
```

Where you can use the chained setters to override any args set in the restart file (likely only used to override endTime) as well as set any parameters that can be used by Data but not set in the restart file.

The old constructor will also still work to not break old code. 
```
  Data data(nx, ny, nz, xmin, xmax, ymin, ymax, zmin, zmax, endTime, &env,
            cfl, Ng, gamma, sigma, cp, mu1, mu2, frameSkip);
```

**Comment by IanHawke** [comment]
This was also tested in https://github.com/AlexJamesWright/METHOD/commit/28418e9314bc16f11709e47e7ea9628ed5915da7 (as noted in https://github.com/AlexJamesWright/METHOD/issues/35) and works well.
