### ISSUE TITLE
Saving seed and other optional parameters to HDF5

### ISSUE THREAD

**Issue by aniabrown** [AlexJamesWright/METHOD#35]
From PR #29 "The one thing that springs to mind here is the random seed (seed in main.cc). I would usually encode this in the filename - that's how the output was dealt with previously - but I now wonder about also storing it in the h5 somewhere. That's a bit of a pain as it's not defined in all cases; if you can't think of an easy way of adding such optional data, let's put it as an issue for future work and we'll encode in the filename again for now."

**Comment by aniabrown** [comment]
I've implemented this by adding optionalSimArgs (array of doubles) and optionalSimArgNames (array of strings) to the Data object and parameter objects used in the Data constructor (DataArgs, SerialCheckpointArgs & ParallelCheckpointArgs). These can be set using the setter functions on the parameter objects and will be automatically read from a checkpoint restart file if reading from one. The args are then available on the Data object for use in the simulation and are written to HDF5 under the 'Optional' group in the HDF5 file. Each optional arg will be written as a separate attribute within the group, with the name provided in the optionalSimArgNames array. 

Limitations: 
* it is not possible to set optional sim args from the old style Data constructor (see Issue #34)
* args can currently only be of type double, and will be cast to double if eg an int is provided. We may want to extend this eventually to have separate arrays for optional ints, strings etc
* optional args are not written to text-format output files, only hdf5

An example of setting optional args is shown in Examples/SingleFluidIdealRandomMPIHDF5 and an example of reading them from checkpoint restart is shown in Examples/SingleFluidIdealRandomMPIHDF5CheckpointRestart

**Comment by IanHawke** [comment]
Tested this in https://github.com/AlexJamesWright/METHOD/commit/28418e9314bc16f11709e47e7ea9628ed5915da7 and it works well.
