### ISSUE TITLE
Ordering of BCs vs SimData construction

### ISSUE THREAD

**Issue by IanHawke** [AlexJamesWright/METHOD#9]
https://github.com/AlexJamesWright/METHOD/blob/6482d373ba69680390c88a129b41828eaf754b5b/Examples/KelvinHelmholtz/SingleFluidIdealRandomParallel/main.cc#L58

As discussed in today's call, the order matters in the calling of these constructors.

Medium/long term it would be good to find a way to enforce this (throw an error if it's done in the wrong order).

**Comment by aniabrown** [comment]
I definitely agree -- the fact that Simulation() needs to be called before initFunc() is currently checked using the memSet flag on Data. I can do something similar for Bcs

**Comment by IanHawke** [comment]
Works.
